# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regi_fixed.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 360, 640))
        self.frame.setStyleSheet("QFrame{\n"
"background-image: url(:/back/back.png);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(28, 310, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(27, 103, 81, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_road = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_road.setGeometry(QtCore.QRect(28, 250, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.lineEdit_road.setFont(font)
        self.lineEdit_road.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.lineEdit_road.setObjectName("lineEdit_road")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(118, 30, 121, 33))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setGeometry(QtCore.QRect(188, 550, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setStyleSheet("background-color: rgba(230, 51, 76, 230);\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(173, 405, 18, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_pa = QtWidgets.QLabel(self.frame)
        self.label_pa.setGeometry(QtCore.QRect(118, 310, 51, 31))
        self.label_pa.setStyleSheet("font: 16pt \"PMingLiU\";")
        self.label_pa.setText("")
        self.label_pa.setObjectName("label_pa")
        self.lineEdit_pn = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_pn.setGeometry(QtCore.QRect(168, 310, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.lineEdit_pn.setFont(font)
        self.lineEdit_pn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.lineEdit_pn.setObjectName("lineEdit_pn")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(28, 200, 301, 36))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_cities = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_cities.setFont(font)
        self.comboBox_cities.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.comboBox_cities.setObjectName("comboBox_cities")
        self.horizontalLayout.addWidget(self.comboBox_cities)
        self.comboBox_area = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_area.setFont(font)
        self.comboBox_area.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.comboBox_area.setObjectName("comboBox_area")
        self.horizontalLayout.addWidget(self.comboBox_area)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(28, 160, 81, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_3.setObjectName("label_3")
        self.timeEdit_start = QtWidgets.QTimeEdit(self.frame)
        self.timeEdit_start.setGeometry(QtCore.QRect(28, 410, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.timeEdit_start.setFont(font)
        self.timeEdit_start.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.timeEdit_start.setObjectName("timeEdit_start")
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_name.setGeometry(QtCore.QRect(138, 103, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(28, 370, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_4.setObjectName("label_4")
        self.timeEdit_end = QtWidgets.QTimeEdit(self.frame)
        self.timeEdit_end.setGeometry(QtCore.QRect(198, 410, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.timeEdit_end.setFont(font)
        self.timeEdit_end.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.timeEdit_end.setObjectName("timeEdit_end")
        self.pushButton_clear = QtWidgets.QPushButton(self.frame)
        self.pushButton_clear.setGeometry(QtCore.QRect(30, 550, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("background-color: rgba(230, 51, 76, 230);\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);")
        self.pushButton_clear.setObjectName("pushButton_clear")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "聯絡電話"))
        self.label_2.setText(_translate("MainWindow", "店家名稱"))
        self.label.setText(_translate("MainWindow", "修改資料"))
        self.pushButton_ok.setText(_translate("MainWindow", "Next"))
        self.label_6.setText(_translate("MainWindow", "~"))
        self.label_3.setText(_translate("MainWindow", "店家地址"))
        self.label_4.setText(_translate("MainWindow", "營業時間"))
        self.pushButton_clear.setText(_translate("MainWindow", "上一步"))

import back_rc
