# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regi_info.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InfoWindow(object):
    def setupUi(self, InfoWindow):
        InfoWindow.setObjectName("InfoWindow")
        InfoWindow.resize(360, 640)
        self.centralwidget = QtWidgets.QWidget(InfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 360, 640))
        self.frame.setStyleSheet("QFrame{\n"
"background-image: url(:/back/back.png);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.add_label = QtWidgets.QLabel(self.frame)
        self.add_label.setGeometry(QtCore.QRect(131, 300, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.add_label.setFont(font)
        self.add_label.setText("")
        self.add_label.setWordWrap(True)
        self.add_label.setObjectName("add_label")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 110, 101, 41))
        self.label_6.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_6.setObjectName("label_6")
        self.mission_Button = QtWidgets.QPushButton(self.frame)
        self.mission_Button.setGeometry(QtCore.QRect(40, 580, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.mission_Button.setFont(font)
        self.mission_Button.setStyleSheet("background-color:rgb(230, 51, 76);\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);")
        self.mission_Button.setObjectName("mission_Button")
        self.pn_label = QtWidgets.QLabel(self.frame)
        self.pn_label.setGeometry(QtCore.QRect(131, 73, 212, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.pn_label.setFont(font)
        self.pn_label.setText("")
        self.pn_label.setObjectName("pn_label")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 310, 80, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 20, 151, 33))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.time_label = QtWidgets.QLabel(self.frame)
        self.time_label.setGeometry(QtCore.QRect(131, 110, 221, 201))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.time_label.setFont(font)
        self.time_label.setText("")
        self.time_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.time_label.setObjectName("time_label")
        self.fixed_Button = QtWidgets.QPushButton(self.frame)
        self.fixed_Button.setGeometry(QtCore.QRect(200, 580, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.fixed_Button.setFont(font)
        self.fixed_Button.setStyleSheet("background-color:rgb(230, 51, 76);\n"
"border-radius:20px;\n"
"color: rgb(255, 255, 255);")
        self.fixed_Button.setObjectName("fixed_Button")
        self.score_label = QtWidgets.QLabel(self.frame)
        self.score_label.setGeometry(QtCore.QRect(280, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.score_label.setFont(font)
        self.score_label.setStyleSheet("border-radius:20px;\n"
"border:2px solid rgb(230, 51, 76);")
        self.score_label.setText("")
        self.score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.score_label.setObjectName("score_label")
        self.pushButton_arrow = QtWidgets.QPushButton(self.frame)
        self.pushButton_arrow.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.pushButton_arrow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_arrow.setIcon(icon)
        self.pushButton_arrow.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_arrow.setObjectName("pushButton_arrow")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.frame)
        self.webEngineView.setGeometry(QtCore.QRect(30, 400, 301, 161))
        self.webEngineView.setUrl(QtCore.QUrl("https://lh3.googleusercontent.com/p/AF1QipPx-4a7lCU73mJ2Nmerms-HSxIzGKzyRbArm51c=s1600-w400"))
        self.webEngineView.setObjectName("webEngineView")
        InfoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InfoWindow)
        QtCore.QMetaObject.connectSlotsByName(InfoWindow)

    def retranslateUi(self, InfoWindow):
        _translate = QtCore.QCoreApplication.translate
        InfoWindow.setWindowTitle(_translate("InfoWindow", "MainWindow"))
        self.label_6.setText(_translate("InfoWindow", "營業時間"))
        self.mission_Button.setText(_translate("InfoWindow", "新增任務"))
        self.label_5.setText(_translate("InfoWindow", "連絡電話"))
        self.label_4.setText(_translate("InfoWindow", "店家地址"))
        self.fixed_Button.setText(_translate("InfoWindow", "修改"))

from PyQt5 import QtWebEngineWidgets
import back_rc
