# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showTask.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_arrow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arrow.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.pushButton_arrow.setText("")
        self.pushButton_arrow.setObjectName("pushButton_arrow")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 341, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.mytask = QtWidgets.QWidget()
        self.mytask.setObjectName("mytask")
        self.line_2 = QtWidgets.QFrame(self.mytask)
        self.line_2.setGeometry(QtCore.QRect(0, 40, 331, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.mytask)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 300, 331, 231))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setObjectName("groupBox_3")
        self.toolButton_9 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_9.setGeometry(QtCore.QRect(240, 190, 81, 31))
        self.toolButton_9.setObjectName("toolButton_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.mytask)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 60, 331, 231))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setObjectName("groupBox_4")
        self.toolButton_8 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_8.setGeometry(QtCore.QRect(240, 190, 81, 31))
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_10 = QtWidgets.QToolButton(self.mytask)
        self.toolButton_10.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.toolButton_10.setObjectName("toolButton_10")
        self.tabWidget.addTab(self.mytask, "")
        self.alltask = QtWidgets.QWidget()
        self.alltask.setObjectName("alltask")
        self.line = QtWidgets.QFrame(self.alltask)
        self.line.setGeometry(QtCore.QRect(0, 40, 331, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.alltask)
        self.groupBox.setGeometry(QtCore.QRect(0, 60, 331, 231))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 311, 41))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 80, 311, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 130, 311, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_more = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_more.setGeometry(QtCore.QRect(237, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_more.setFont(font)
        self.pushButton_more.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_more.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_more.setAutoFillBackground(False)
        self.pushButton_more.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_more.setAutoDefault(False)
        self.pushButton_more.setFlat(False)
        self.pushButton_more.setObjectName("pushButton_more")
        self.groupBox_2 = QtWidgets.QGroupBox(self.alltask)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 300, 331, 231))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName("groupBox_2")
        self.toolButton_7 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_7.setGeometry(QtCore.QRect(240, 190, 81, 31))
        self.toolButton_7.setObjectName("toolButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 30, 311, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 80, 311, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 130, 311, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.toolButton_5 = QtWidgets.QToolButton(self.alltask)
        self.toolButton_5.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.toolButton_5.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_5.setObjectName("toolButton_5")
        self.tabWidget.addTab(self.alltask, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "一般任務"))
        self.toolButton_9.setText(_translate("MainWindow", "more..."))
        self.groupBox_4.setTitle(_translate("MainWindow", "每日任務"))
        self.toolButton_8.setText(_translate("MainWindow", "more..."))
        self.toolButton_10.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mytask), _translate("MainWindow", "      我的任務      "))
        self.groupBox.setTitle(_translate("MainWindow", "每日任務"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_more.setText(_translate("MainWindow", "more..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "一般任務"))
        self.toolButton_7.setText(_translate("MainWindow", "more..."))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alltask), _translate("MainWindow", "      所有任務      "))

