# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_signin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(360, 640)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("QDialog{\n"
"    background-image: url(:/back/back.png);\n"
"}")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(50, 260, 59, 50))
        self.label_10.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("華康粗圓體")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(50, 120, 51, 81))
        self.label_9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("華康粗圓體")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(230, 51, 76);")
        self.label_9.setIndent(-1)
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(130, 30, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.pushButton_register = QtWidgets.QPushButton(Dialog)
        self.pushButton_register.setGeometry(QtCore.QRect(70, 530, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    color: rgb(109, 109, 109);\n"
"}")
        self.pushButton_register.setObjectName("pushButton_register")
        self.pushButton_signin = QtWidgets.QPushButton(Dialog)
        self.pushButton_signin.setEnabled(True)
        self.pushButton_signin.setGeometry(QtCore.QRect(40, 470, 281, 47))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 51, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_signin.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("華康粗圓體")
        font.setPointSize(12)
        self.pushButton_signin.setFont(font)
        self.pushButton_signin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_signin.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_signin.setAcceptDrops(False)
        self.pushButton_signin.setToolTipDuration(-1)
        self.pushButton_signin.setAutoFillBackground(False)
        self.pushButton_signin.setStyleSheet("QPushButton{\n"
"    background-color:rgb(230, 51, 76);\n"
"    border-radius:20px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_signin.setAutoDefault(True)
        self.pushButton_signin.setDefault(False)
        self.pushButton_signin.setFlat(False)
        self.pushButton_signin.setObjectName("pushButton_signin")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(50, 210, 271, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(50, 330, 271, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_email1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_email1.setEnabled(True)
        self.lineEdit_email1.setGeometry(QtCore.QRect(50, 180, 271, 34))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.lineEdit_email1.setFont(font)
        self.lineEdit_email1.setStyleSheet("background:transparent")
        self.lineEdit_email1.setMaxLength(50)
        self.lineEdit_email1.setFrame(False)
        self.lineEdit_email1.setObjectName("lineEdit_email1")
        self.lineEdit_pass1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_pass1.setEnabled(True)
        self.lineEdit_pass1.setGeometry(QtCore.QRect(50, 300, 271, 34))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.lineEdit_pass1.setFont(font)
        self.lineEdit_pass1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_pass1.setAutoFillBackground(False)
        self.lineEdit_pass1.setStyleSheet("background:transparent")
        self.lineEdit_pass1.setMaxLength(50)
        self.lineEdit_pass1.setFrame(False)
        self.lineEdit_pass1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pass1.setCursorPosition(0)
        self.lineEdit_pass1.setDragEnabled(False)
        self.lineEdit_pass1.setReadOnly(False)
        self.lineEdit_pass1.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_pass1.setClearButtonEnabled(False)
        self.lineEdit_pass1.setObjectName("lineEdit_pass1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "密碼"))
        self.label_9.setText(_translate("Dialog", "信箱"))
        self.label_7.setText(_translate("Dialog", "帳號登入"))
        self.pushButton_register.setText(_translate("Dialog", "還沒有帳號嗎?請註冊"))
        self.pushButton_signin.setText(_translate("Dialog", "登入"))

import back_rc
